TurboFishShop/Controllers/CartController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity.UI.Services;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using TurboFishShop_Data;
using TurboFishShop.Models;
using TurboFishShop.Models.ViewModels;
using TurboFishShop_Models;
using TurboFishShop_Models.ViewModels;
using TurboFishShop_Utility;

namespace TurboFishShop.Controllers
{
    [Authorize]
    public class CartController : Controller
    {
        ApplicationDBContext db;

		ProductUserViewModel productUserViewModel;

		IWebHostEnvironment webHostEnvironment;

		IEmailSender emailSender;

		public CartController(ApplicationDBContext db, IWebHostEnvironment webHostEnvironment, IEmailSender emailSender)
		{
            this.db = db;
			this.webHostEnvironment = webHostEnvironment;
			this.emailSender = emailSender;
		}

        public IActionResult Index()
        {
            List<Cart> cartList = new List<Cart>();

            if (HttpContext.Session.Get<IEnumerable<Cart>>(PathsManager.SessionCart) != null &&
                HttpContext.Session.Get<IEnumerable<Cart>>(PathsManager.SessionCart).Count() > 0)
            {
                cartList = HttpContext.Session.Get<List<Cart>>(PathsManager.SessionCart);

                // хотим получить список товаров, которые находятся в корзине
            }

			List<int> productsIdInCart = cartList.Select(p => p.ProductId).ToList();

			//извлекаем сами продукты по списку id
			IEnumerable<Product> productList = db.Product.Where(p => productsIdInCart.Contains(p.Id));

			return View(productList);
        }

        public IActionResult Remove(int id)
        {
			List<Cart> cartList = new List<Cart>();

			if (HttpContext.Session.Get<IEnumerable<Cart>>(PathsManager.SessionCart) != null &&
				HttpContext.Session.Get<IEnumerable<Cart>>(PathsManager.SessionCart).Count() > 0)
			{
				cartList = HttpContext.Session.Get<List<Cart>>(PathsManager.SessionCart);
			}

			cartList.Remove(cartList.Where(p => p.ProductId == id).FirstOrDefault());

            // переназначить сессию
			HttpContext.Session.Set(PathsManager.SessionCart, cartList);

			return RedirectToAction(nameof(Index));
		}

		public IActionResult InquiryConfirmation()
		{
			HttpContext.Session.Clear(); // очистить данные сессии
			
			return View();
		}


		[HttpPost]
		public async Task<IActionResult> SummaryPost(ProductUserViewModel productUserViewModel)
		{
			// код для отправки сообщения
			// combine
			var path = webHostEnvironment.WebRootPath += Path.DirectorySeparatorChar.ToString() +
				"templates" + Path.DirectorySeparatorChar.ToString() + "Inquiry.html";

			var subject = "New Order";

			var bodyHtml = "";

			using (StreamReader reader = new StreamReader(path))
			{
				bodyHtml = reader.ReadToEnd();
			}

			string textProducts = "";
			foreach (var item in productUserViewModel.ProductList)
			{
				textProducts += $"- Name: {item.Name}, ID: {item.Id}\n";
			}

			string body = string.Format(bodyHtml, 
				productUserViewModel.ApplicationUser.FullName,
				productUserViewModel.ApplicationUser.Email, 
				productUserViewModel.ApplicationUser.PhoneNumber, 
				textProducts);

			await emailSender.SendEmailAsync(productUserViewModel.ApplicationUser.Email, subject, body);
			await emailSender.SendEmailAsync("Max2827@yandex.ru", subject, body);

			return RedirectToAction("InquiryConfirmation");
		}

		[HttpPost]
		public IActionResult Summary()
        {
			ClaimsIdentity claimsIdentity = (ClaimsIdentity)User.Identity;

            // если пользователь вошёл в систему, то объект будет определён
			Claim claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);

            List<Cart> cartList = new List<Cart>();

			if (HttpContext.Session.Get<IEnumerable<Cart>>(PathsManager.SessionCart) != null &&
				HttpContext.Session.Get<IEnumerable<Cart>>(PathsManager.SessionCart).Count() > 0)
			{
				cartList = HttpContext.Session.Get<List<Cart>>(PathsManager.SessionCart);
			}

			List<int> productsIdInCart = cartList.Select(p => p.ProductId).ToList();

			IEnumerable<Product> productList = db.Product.Where(p => productsIdInCart.Contains(p.Id));

			productUserViewModel = new ProductUserViewModel()
			{
				ApplicationUser = db.ApplicationUsers.FirstOrDefault(x => x.Id == claim.Value),
				ProductList = productList.ToList()
			};

			return View(productUserViewModel);
		}

	}
}

TurboFishShop/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Data;
using TurboFishShop_Data;
using TurboFishShop.Models;
using TurboFishShop_Models;
using TurboFishShop_Utility;

namespace TurboFishShop.Controllers
{
	[Authorize(Roles = PathsManager.AdminRole)]
	public class CategoryController : Controller
    {
        private ApplicationDBContext db;

        public CategoryController(ApplicationDBContext db)
        {
            this.db = db;
        }

        public IActionResult Index()
        {
            IEnumerable<Category> categories =  db.Categories;

            return View(categories);
        }

        // GET - Create
        public IActionResult Create()
        {
            return View();
        }

        // POST - Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Category category)
        {
            if (ModelState.IsValid) // проверка модели на валидность
            {
                db.Categories.Add(category);
                db.SaveChanges();
                return RedirectToAction("Index"); //переход на страницу Index
            }

            return View(category);
        }

        // GET - Edit
        [HttpGet]
        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            var category = db.Categories.Find(id);

            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        //POST - Edit
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Category category)
        {
            if (ModelState.IsValid) // проверка модели на валидность
            {
                db.Categories.Update(category);  // !!!
                db.SaveChanges();
                return RedirectToAction("Index"); //переход на страницу Index
            }

            return View(category);
        }

        // GET - Delete
        [HttpGet]
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            var category = db.Categories.Find(id);

            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        //POST - Delete
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePost(int? id)
        {
            var category = db.Categories.Find(id);

            if (category == null)
            {
                return NotFound();
            }

            db.Categories.Remove(category);
            db.SaveChanges();

            return RedirectToAction("Index");
        }
    }
}

TurboFishShop/Controllers/MyModelController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Data;
using TurboFishShop_Data;
using TurboFishShop.Models;
using TurboFishShop_Models;
using TurboFishShop_Utility;

namespace TurboFishShop.Controllers
{
	[Authorize(Roles = PathsManager.AdminRole)]
	public class MyModelController : Controller
    {
        private ApplicationDBContext db;

        public MyModelController(ApplicationDBContext db)
        {
            this.db = db;
        }

        public IActionResult Index()
        {
            IEnumerable<MyModel> models = db.MyModels;

            return View(models);
        }

        // GET - Create
        public IActionResult Create()
        {
            return View();
        }

        // POST - Create
        [HttpPost]
        public IActionResult Create(MyModel model)
        {
            if (model == null || model.Name == null)
                return RedirectToAction("Index");
            db.MyModels.Add(model);
            db.SaveChanges();

            return RedirectToAction("Index");  //переход на страницу Index
        }

		// GET - Edit
		[HttpGet]
		public IActionResult Edit(int? id)
		{
			if (id == null || id == 0)
			{
				return NotFound();
			}

			var model = db.MyModels.Find(id);

			if (model == null)
			{
				return NotFound();
			}

			return View(model);
		}

		//POST - Edit
		[HttpPost]
		[ValidateAntiForgeryToken]
		public IActionResult Edit(MyModel model)
		{
			if (ModelState.IsValid) // проверка модели на валидность
			{
				db.MyModels.Update(model);  // !!!
				db.SaveChanges();
				return RedirectToAction("Index"); //переход на страницу Index
			}

			return View(model);
		}

		// GET - Delete
		[HttpGet]
		public IActionResult Delete(int? id)
		{
			if (id == null || id == 0)
			{
				return NotFound();
			}

			var model = db.MyModels.Find(id);

			if (model == null)
			{
				return NotFound();
			}

			return View(model);
		}

		//POST - Delete
		[HttpPost]
		[ValidateAntiForgeryToken]
		public IActionResult DeletePost(int? id)
		{
			var model = db.MyModels.Find(id);

			if (model == null)
			{
				return NotFound();
			}

			db.MyModels.Remove(model);
			db.SaveChanges();

			return RedirectToAction("Index");
		}
	}
}

TurboFishShop/Controllers/ProductController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.IO;
using TurboFishShop_Data;
using TurboFishShop.Models;
using TurboFishShop.Models.ViewModels;
using TurboFishShop_Models;
using TurboFishShop_Utility;

namespace TurboFishShop.Controllers
{
	[Authorize(Roles = PathsManager.AdminRole)]
	public class ProductController : Controller
	{
        private ApplicationDBContext db;
        private IWebHostEnvironment webHostEnvironment;

        public ProductController(ApplicationDBContext db, IWebHostEnvironment webHostEnvironment)
        {
            this.db = db;
            this.webHostEnvironment = webHostEnvironment;
        }
        
        // GET INDEX
        public IActionResult Index()
		{
            IEnumerable<Product> objList =  db.Product;
            /*
            // получаем ссылки на сущности категорий
            foreach (var item in objList)
            {
                item.Category = db.Categories.FirstOrDefault(x => x.Id == item.CategoryId);
            }
            */
			return View(objList);
		}

		// GET - CreateEdit
		public IActionResult CreateEdit(int? id)
		{
			/*
            // получаем лист категорий для отправки его во View
            IEnumerable<SelectListItem> CategoriesList = db.Category.Select(x =>
                new SelectListItem
                {
                    Text = x.Name,
                    Value = x.Id.ToString()
                });
            // отправляем лист категорий во View
            //ViewBag.CategoriesList = CategoriesList;
            ViewData["CategoriesList"] = CategoriesList;
            */

			ProductViewModel productViewModel = new ProductViewModel()
			{
				Product = new Product(),
				CategoriesList = db.Categories.Select(x =>
				new SelectListItem
				{
					Text = x.Name,
					Value = x.Id.ToString()
				}),
				MyModelsList = db.MyModels.Select(x =>
				new SelectListItem
				{
					Text = x.Name,
					Value = x.Id.ToString()
				})
			};

			if (id == null)
			{
				// create product
				return View(productViewModel);
			}
			else
			{
				// edit product
				productViewModel.Product = db.Product.Find(id);

				if (productViewModel.Product == null)
				{
					return NotFound();
				}
				return View(productViewModel);
			}
		}

		// POST - CreateEdit
		[HttpPost]
		[ValidateAntiForgeryToken]
		public IActionResult CreateEdit(ProductViewModel productViewModel)
		{
			var files = HttpContext.Request.Form.Files;

			string wwwRoot = webHostEnvironment.WebRootPath;

			if (productViewModel.Product.Id == 0)
			{
				// create
				string upload = wwwRoot + PathsManager.ImageProductPath;
				string imageName = Guid.NewGuid().ToString();

				string extension = Path.GetExtension(files[0].FileName);

				string path = upload + imageName + extension;

				// скопируем файл на сервер
				using (var fileStream = new FileStream(path, FileMode.Create))
				{
					files[0].CopyTo(fileStream);
				}

				productViewModel.Product.Image = imageName + extension;

				db.Product.Add(productViewModel.Product);
			}
			else
			{
				// update
				// AsNoTracking() importamt !
				var product  = db.Product.AsNoTracking().FirstOrDefault(u => u.Id == productViewModel.Product.Id);

				if (files.Count > 0) // юзер загружает другой файл
				{
					string upload = wwwRoot + PathsManager.ImageProductPath;
					string imageName = Guid.NewGuid().ToString();

					string extension = Path.GetExtension(files[0].FileName);
					string path = upload + imageName + extension;

					// delete old file
					var oldFile = upload + product.Image;

					if (System.IO.File.Exists(oldFile))
					{
						System.IO.File.Delete(oldFile);
					}

					// скопируем файл на сервер
					using (var fileStream = new FileStream(path, FileMode.Create))
					{
						files[0].CopyTo(fileStream);
					}

					productViewModel.Product.Image = imageName + extension;
				}
				else // фотка не поменялась
				{
					productViewModel.Product.Image = product.Image;  // оставляем имя прежним
				}

				db.Product.Update(productViewModel.Product);
			}

			db.SaveChanges();

			return RedirectToAction("Index");
		}

		// GET - DELETE
		[HttpGet]
		public IActionResult Delete(int? id)
		{
			if (id == null || id == 0)
			{
				return NotFound();
			}
			var product = db.Product.Find(id);
			if (product == null)
			{
				return NotFound();
			}
			product.Category = db.Categories.Find(product.CategoryId);
			product.MyModel = db.MyModels.Find(product.MyModelId);

			return View(product);
		}

		// POST
		[HttpPost]
		public IActionResult DeletePost(int? id)
		{
			if (id == null || id == 0)
			{
				return NotFound();
			}
			var product = db.Product.Find(id);

			string upload = webHostEnvironment.WebRootPath + PathsManager.ImageProductPath;

			var oldFile = upload + product.Image;

			if (System.IO.File.Exists(oldFile))
				System.IO.File.Delete(oldFile);

			db.Product.Remove(product);
			db.SaveChanges();

			return RedirectToAction("Index");
		}
	}
}

TurboFishShop/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
@using TurboFishShop_Utility;
@inject IHttpContextAccessor HttpContextAccessor

<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] - TurboFishShop</title>
	<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
	<link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
	<link rel="stylesheet" href="~/TurboFishShop.styles.css" asp-append-version="true" />
	<link rel="stylesheet" href="~/fontawesome/css/all.css" />
	<link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.css" rel="stylesheet">
</head>
<body>
	<header>
		<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
			<div class="container-fluid">
				<a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TurboFishShop</a>
				<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
						aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
				<div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">

					<partial name="_LoginPartial" />

					<ul class="navbar-nav flex-grow-1">
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
						</li>
						
						@if(User.IsInRole(PathsManager.AdminRole))
						{
							<li class="nav-item dropdown">
								<a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
								Managment
								</a>
								<ul class="dropdown-menu">
									<li class="nav-item">
										<a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="Index">Category</a>
									</li>
									<li class="nav-item">
										<a class="nav-link text-dark" asp-area="" asp-controller="MyModel" asp-action="Index">MyModel</a>
									</li>
									<li class="nav-item">
										<a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Index">Product</a>
									</li>
									
									<div class="dropdown-divider"></div>
									
									<li class="nav-item">
										<a class="nav-link text-dark" asp-area="Identity" asp-page="/Account/Register">Register Admin User</a>
									</li>
								</ul>
							</li>
						}
						

						<li>
							@if (HttpContextAccessor.HttpContext.Session.Get<List<Cart>>(PathsManager.SessionCart) != null)
							{
								var count = HttpContextAccessor.HttpContext.Session.Get<List<Cart>>(PathsManager.SessionCart).Count;

								<a asp-controller="Cart" class="nav-link">
									<i class="fas fa-shopping-cart"></i> &nbsp; (@count)
								</a>
							}
							else
							{
								<a asp-controller="Cart" class="nav-link">
									<i class="fas fa-shopping-cart"></i> &nbsp; (0)
								</a>
							}
						</li>
					</ul>
				</div>
			</div>
		</nav>
	</header>
	<div class="container">
		<main role="main" class="pb-3">
			@RenderBody()
		</main>
	</div>

	<footer class="border-top footer text-muted">
		<div class="container">
			&copy; 2022 - TurboFishShop - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
		</div>
	</footer>
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>
	<script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
	<!-- include summernote css/js -->
	<script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.js"></script>
	@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

TurboFishShop/Views/Shared/_ProductCard.cshtml
@using TurboFishShop_Utility;
@model TurboFishShop_Models.Product

<div class="card filter @Model.Category.Name.Replace(' ', '_') " style="display:flex;float:left; width: 18rem; height:25rem; margin: 5px; border: groove; border-width:2px;">
    <img src="@PathsManager.ImageProductPath@Model.Image" class="card-img-top" alt="...">
    <div class="card-body">
        <h5 class="card-title">@Model.Name</h5>
        <p class="card-text">@Model.ShortDescription</p>
        <span class="badge text-bg-primary">Primary</span>
		<!-- controller дефолтный -->
        <a asp-action="Details" asp-route-Id="@Model.Id" class="btn btn-primary">Detail</a>
    </div>
</div>